{
	"version": 1763098545,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btngoogleplay-sheet0.png",
		"images/btnaddsite-sheet0.png",
		"images/btnvideo-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btnmore-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnback-sheet0.png",
		"images/btnbuy-sheet0.png",
		"images/btnbuygold-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnshop-sheet0.png",
		"images/btnshopcoin-sheet0.png",
		"images/bg-sheet0.png",
		"images/txtgold.png",
		"images/txtstatic.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/vfxshineresult-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr650x1024-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/foption-sheet0.png",
		"images/overlay-sheet0.png",
		"images/uiscore-sheet0.png",
		"images/uigold-sheet0.png",
		"images/game-sheet0.png",
		"images/road-sheet0.png",
		"images/mode7cam-sheet0.png",
		"images/lastobjectobstacle-sheet0.png",
		"images/gold-sheet0.png",
		"images/gold-sheet1.png",
		"images/flashwhite-sheet0.png",
		"images/objobstacle-sheet0.png",
		"images/green-sheet0.png",
		"images/tree0-sheet0.png",
		"images/stone-sheet0.png",
		"images/tree5-sheet0.png",
		"images/tree4-sheet0.png",
		"images/tree3-sheet0.png",
		"images/tree1-sheet0.png",
		"images/tree2-sheet0.png",
		"images/obstacle0-sheet0.png",
		"images/obstacle2-sheet0.png",
		"images/obstacle1-sheet0.png",
		"images/char0-sheet0.png",
		"images/char0-sheet1.png",
		"images/charshadow-sheet0.png",
		"images/char1-sheet0.png",
		"images/char1-sheet1.png",
		"images/char2-sheet0.png",
		"images/char2-sheet1.png",
		"images/char3-sheet0.png",
		"images/char3-sheet1.png",
		"images/char4-sheet0.png",
		"images/char4-sheet1.png",
		"images/char5-sheet0.png",
		"images/char5-sheet1.png",
		"images/opacityingame-sheet0.png",
		"images/opacityingameground-sheet0.png",
		"images/vfxabsorb-sheet0.png",
		"images/vfxgold-sheet0.png",
		"images/vfxgold-sheet1.png",
		"images/vfxhit-sheet0.png",
		"images/vfxshine-sheet0.png",
		"images/vfxshield-sheet0.png",
		"images/vfxdustrun-sheet0.png",
		"images/vfxdustrun-sheet1.png",
		"images/vfxdustrun-sheet2.png",
		"images/vfxdustslide-sheet0.png",
		"images/vfxdustslide-sheet1.png",
		"images/vfxdustslide-sheet2.png",
		"images/vfxpowerup-sheet0.png",
		"images/vfxpowerup-sheet1.png",
		"images/powupmagnet-sheet0.png",
		"images/powupmultiply-sheet0.png",
		"images/powupshield-sheet0.png",
		"images/showmultiply-sheet0.png",
		"images/fshopchar-sheet0.png",
		"images/uibuychar-sheet0.png",
		"images/uibuychar-sheet1.png",
		"images/uibuygold-sheet0.png",
		"images/uigoldshop-sheet0.png",
		"images/fshopgold-sheet0.png",
		"images/uititle-sheet0.png",
		"images/ftutorial-sheet0.png",
		"images/key-sheet0.png",
		"images/arrow-sheet0.png",
		"images/touchtutorial-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/not enough gold.m4a",
		"media/not enough gold.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/char jump.m4a",
		"media/char jump.ogg",
		"media/char hit.m4a",
		"media/char hit.ogg",
		"media/char crash.m4a",
		"media/char crash.ogg",
		"media/char slide.m4a",
		"media/char slide.ogg",
		"media/char move.m4a",
		"media/char move.ogg",
		"media/step.m4a",
		"media/step.ogg",
		"media/death.m4a",
		"media/death.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}